sudo: required
services:
  - docker

# before_install:
  # - docker build -t beatsbyalif/pico-test -f ./front/DockerFile.dev ./front

script:
  # - docker run -e CI=true beatsbyalif/pico-test npm run test -- --coverage
  - echo "Hellooo"

after_success:
  - docker build -t beatsbyalif/mysite-front ./front
  - docker build -t beatsbyalif/mysite-server ./server
  - docker build -t beatsbyalif/mysite-nginx ./nginx
  # Login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images
  - docker push beatsbyalif/mysite-front
  - docker push beatsbyalif/mysite-server
  - docker push beatsbyalif/mysite-nginx

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "MySite"
  env: "MySite-env"
  bucket_name: "elasticbeanstalk-us-east-2-246211615161"
  bucket_path: "MySite"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY